name: Python Package and Release

on:
  push:
    tags:
      - '*'  # 当有新标签被推送时触发工作流

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: |
        python setup.py bdist_wheel

    - name: Upload whleel file
      uses: actions/upload-artifact@v4
      with:
        name: occrq-juejin-python-sdk.whl
        path: dist/occrq_juejin_python_sdk-0.1.0-py3-none-any.whl

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
          tag_name: ${{ github.ref_name }}
          files: |
            */occrq-juejin-python-sdk.whl
